In [12]:
import numpy as np

# 数组保存于加载

In [17]:
# 保存数组
x = np.array([1, 2, 3, 4, 5])
np.save('my_array', x)

In [19]:
# 加载数组
y = np.load('my_array.npy')
print('y = ', y)


y =  [1 2 3 4 5]


# 创建常见数组形式

In [20]:
#创建指定数组形状及值
C = np.full((2,3), 6) 
C

array([[6, 6, 6],
       [6, 6, 6]])

In [47]:
# 创建一个 5*5的单位矩阵
X = np.eye(5)
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# 创建 对角矩阵
X = np.diag([10,20,30,50])
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

# 一维数组创建

In [26]:
# 指定一维数组
x =c np.arange(10)
y = np.arange(4, 10)
z = np.arange(1, 14, 3)
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]


In [32]:
#返回10个在0-25之间的均匀分布的浮点数字
x = np.linspace(0,25,10)

#不含起始和结束点
y = np.linspace(0,25,10, endpoint = False)
print(x)
print(y)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


# 修改数组形状

In [33]:
#修改以为数组大小
Y = np.arange(20).reshape(4, 5)
Y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 创建随机数组

In [36]:
# 创建指定大小的随机ndarry，0-1内的随机浮点数。
X = np.random.random((3,3))

#指定数据范围
Y = np.random.randint(4,15,size=(3,2))

print(X)
print(Y)

[[0.06054342 0.66068495 0.94297463]
 [0.80370054 0.96832744 0.30043012]
 [0.78666586 0.49637295 0.52625935]]
[[14 14]
 [ 7 10]
 [ 6  5]]


# 正太分布 数组

In [37]:
#创建一个包含 正态分布（均值为 0，标准差为 0.1）中随机抽样的浮点数。
X = np.random.normal(0, 0.1, size=(1000,1000))
X

array([[-0.0302019 ,  0.08131563,  0.02227273, ..., -0.07521239,
        -0.09607714,  0.02175025],
       [ 0.05963208, -0.01013994,  0.00922513, ..., -0.02493592,
        -0.03421897, -0.11822773],
       [-0.00309181, -0.00715625, -0.08278673, ..., -0.02332284,
        -0.25053045, -0.22345875],
       ...,
       [ 0.03362342, -0.02304741,  0.03240952, ..., -0.02188135,
         0.08411762, -0.07909923],
       [-0.0696199 , -0.02060168,  0.12107444, ...,  0.05233584,
         0.11508142,  0.04528012],
       [-0.08131511,  0.07955907, -0.00819523, ..., -0.17679632,
        -0.09863227, -0.05715973]])

In [38]:
X.mean()

-8.28767208005404e-05

In [45]:
#最大最小值
X.max()
X.min()

-0.5208014340638105

In [44]:
#x<0的数量
(X < 0).sum()

500194