In [1]:
import numpy as np

# 访问和修改数据

In [2]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(X[0,0])

X[0,0] = 20

print(X[0,0])

1
20


# 删除数据

In [3]:
x = np.array([1, 2, 3, 4, 5])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('Original x = ', x)

Original x =  [1 2 3 4 5]


In [4]:
# We delete the first and last element of x
x = np.delete(x, [0,4])
x

array([2, 3, 4])

In [5]:
# We delete the first row of y
print(Y)
w = np.delete(Y, 0, axis=0)
w

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)
v

array([[2],
       [5],
       [8]])

# 添加数据

In [7]:
print(x)
x = np.append(x, [7,8])
x

[2 3 4]


array([2, 3, 4, 7, 8])

In [8]:
# We append a new row containing 7,8,9 to y
print(Y)
v = np.append(Y, [[7,8,9]], axis=0)
v

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [9]:
# We append a new column containing 9 and 10 to y
print(Y)
q = np.append(Y,[[9],[10],[11]], axis=1)
q

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 11]])

# 指定位置添加数据

In [10]:
x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3],[7,8,9]])

print(x)

[1 2 5 6 7]


In [11]:
# 在x数组的 第二个位置 添加 数据
x = np.insert(x,2,[3,4])
x

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# 在行方向上 索引号码为1的位置，添加数据
print(Y)
w = np.insert(Y,1,[4,5,6],axis=0)
w

[[1 2 3]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# 在列方向的第一个位置添加数据
print(Y)
v = np.insert(Y,1,5, axis=1)
v

[[1 2 3]
 [7 8 9]]


array([[1, 5, 2, 3],
       [7, 5, 8, 9]])

# 堆叠数据

In [14]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

In [15]:
#垂直堆叠 x在Y的上边
# We stack x on top of Y
z = np.vstack((x,Y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
# 水平堆叠 x在Y的右边
# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))
w

array([[3, 4, 1],
       [5, 6, 2]])